name: reverse-proxy
services:
    nginx:
        image: nginx:alpine
        container_name: reverse-proxy-nginx
        hostname: reverse-proxy-nginx
        volumes:
            - ./conf:/etc/nginx/conf.d:ro
            - ./certbot/conf:/etc/letsencrypt:ro
            - ./certbot/www:/var/www/certbot:ro
        ports:
            - ${PORT_HTTP:-8080}:80
            - ${PORT_HTTPS:-8443}:443
        restart: unless-stopped
    certbot:
        image: certbot/certbot
        container_name: reverse-proxy-certbot
        hostname: reverse-proxy-certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
    app:
        image: golang:1.21.10-alpine
        container_name: reverse-proxy-app
        hostname: reverse-proxy-app
        volumes:
            - ./app:/app:rw
            - ./.env:/.env:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /app
        command: sh -c "go build -o main . && ./main"
        restart: unless-stopped

networks:
  default:
    name: reverse-proxy-network
